### PR TITLE
Feature postgresql dependency

### PR DESCRIPTION
**Pull request by muralikarthikk**

### CODE REVIEW

**Review by pj-linebaugh — APPROVED** [review]
Looks pretty good to me.  Would be nice if it could auto-generate the passwords.  Doesn't look like the Bitnami chart does that, so unsure how that could be done.

**Review by cschreep — CHANGES_REQUESTED** [review]
This is good on its own, but it's important to note that the airflow deployments also define a postgresql dependency. We can have deployment configuration issues if we try to deploy postgresql twice. I would request that this feature be reworked so that we can either tell the appstore to set up its own postgres instance or pass in connection info for an existing postgres deployment

**Comment by muralikarthikk** [comment]
> Looks pretty good to me. Would be nice if it could auto-generate the passwords. Doesn't look like the Bitnami chart does that, so unsure how that could be done.

Yes, you are right. I haven't come across any such setting. I am not sure either.

**Comment by muralikarthikk** [comment]
> This is good on its own, but it's important to note that the airflow deployments also define a postgresql dependency. We can have deployment configuration issues if we try to deploy postgresql twice. I would request that this feature be reworked so that we can either tell the appstore to set up its own postgres instance or pass in connection info for an existing postgres deployment

That makes sense. I am not aware of the airflow postgresql.

**Comment by muralikarthikk** [comment]
I think we can go ahead with the merge once an appstore image is ready. 
We can disable the bitnami postgresql chart and just pass the connection info for an already existing postgresql instance through the values file.

**Review by cschreep — APPROVED** [review]

**Pull request merged**
