### PR TITLE
modify so the ALLOW_SAML_LOGIN variable is always set in container

### PR DESCRIPTION
**Pull request by pj-linebaugh**

### CODE REVIEW

**Comment by waTeim** [comment]
does this cause things to blow up if you're trying to develop locally (no SAML is possible)?

**Comment by frostyfan109** [comment]
I'm kinda confused why we'd want ALLOW_SAML_LOGIN to be set to true in the container if there aren't SAML credentials (e.g. authority url) present!

**Comment by pj-linebaugh** [comment]
I think the variable name is misleading.  If the value is "false" then the UNC login button will not be shown on the login page.

**Comment by frostyfan109** [comment]
Yeah, but the logout button should only be shown with these credentials present anyways, no?

**Comment by pj-linebaugh** [comment]
The ALLOW_SAML_LOGIN variable is checked in the container and if it is set to 'true' then the UNC login button is shown.  This change just makes it so that the ALLOW_SAML_LOGIN variable is always defined in the container.

**Comment by frostyfan109** [comment]
AppStore uses false for this value when it isn't set in the environment

**Comment by frostyfan109** [comment]
I'm just trying to understand why this change is important because it seems like it could lead to accidentally enabling saml when it won't be functional

**Comment by pj-linebaugh** [comment]
When I was troubleshooting the problem that wasn't apparent to me so I changed the chart so that it is always set.  I'm leaving it in b/c I think it's better to declare it than to not declare it.

**Review by frostyfan109 — APPROVED** [review]

**Pull request merged**
