### PR TITLE
Ohdsi parameterize db

### PR DESCRIPTION
**Pull request by muralikarthikk**

### CODE REVIEW

**Review by pj-linebaugh — APPROVED** [review]
I will approve to make things go quicker, but I think these chart commits in the develop branch should work to deploy the app.  So the appVersion (which is used as image.tag by default) should exist as an image tag within the image repo.  Either that or image.tag that corresponds to an existing image tag should be set in the values (this should be changed back to "" before merging to master).  When this PR is merged into develop then flux will try to deploy it to helx-dev and that will fail b/c the image doesn't exist.  Another option (which Jeff doesn't like) would be to manually add the 1.4.2-develop tag to whichever appstore image this is meant for).

**Comment by pj-linebaugh** [comment]
We also discussed setting the appVersion to something like 1.4.2 (in this case) and then also setting the image.tag in values to a working image.  Adding a note in Chart.yaml that appVersion is not used for the image tag and image.tag is, would be good info.  I think we can go with this option in the near future.

**Comment by waTeim** [comment]
This is definitely a new feature, so should be 1.4.x, unless it was previously updated to 1.3 in this same branch.

**Comment by muralikarthikk** [comment]
> This is definitely a new feature, so should be 1.4.x, unless it was previously updated to 1.3 in this same branch.

version changed to 1.4.0

**Review by waTeim — APPROVED** [review]

**Comment by pj-linebaugh** [comment]
There was already a 1.4.0 and 1.4.1 was in process (I created 1.4.1-develop).  So should probably be 1.4.1 or 1.4.2.

**Pull request merged**
